eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: data
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  #配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/translate?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    hots: localhost
    port: 6379
    password: 123456
#mybatis配置
mybatis-plus:
  typeAliasesPackage: com.vencent.transclouddata.entity
  mapperLocations: classpath*:com/vencent/transclouddata/mapper/*.xml
  #configLocation: classpath:/mybatis-config.xml

server:
  port: 8001
  maxPostSize : -1
  maxHttpHeaderSize: 2048000