spring:
  application:
    name: translate
  #文件上传
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  #配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/translate?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:3306/translate??useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    hots: localhost
    port: 6379
    password: 123456
#mybatis配置
#mybatis:
#  typeAliasesPackage: com.vencent.transcloudtranslate.entity
mybatis-plus:
  mapper-locations: classpath*:com/vencent/transcloudtranslate/mapper/*.xml
  typeAliasesPackage: com.vencent.transcloudtranslate.entity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
server:
  port: 8002
  maxPostSize: -1
  maxHttpHeaderSize: 102400
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000
#fegin:
#  hystrix:
#    enabled: true
